apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: postgresdb
          image: mysql:latest
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-secret-credentials
