stages:         
  - build
  - test
  - deploy
# variables:
#   DOCKER_HOST: tcp://docker:2376
#   DOCKER_TLS_CERTDIR: ""

# build:
#   image: $CI_RESIGTRY2:$CI_REGISTRY_PORT/docker:20.10.16
#   stage: build

#   services:
#     - name: $CI_RESIGTRY2:$CI_REGISTRY_PORT/docker:20.10.16-dind
#       alias: docker
#       command:
#         [
#          "--insecure-registry",
#          "172.31.2.126:5000"
#         ]
         
#   script:
#     - docker build -t $CI_RESIGTRY2:$CI_REGISTRY_PORT/v1:$CI_COMMIT_SHORT_SHA .
#     - docker push $CI_RESIGTRY2:$CI_REGISTRY_PORT/v1:$CI_COMMIT_SHORT_SHA


build:
  image: docker
  stage: build
  services:
    - name: docker:dind
      alias: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/root/k8s-data/image:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY/root/k8s-data/image:$CI_COMMIT_SHORT_SHA




deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  variables:
    KUBE_CONTEXT: root/k8s-connection:k8s-connection
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl config view
    - kubectl get pods


    