stages:         
  - build
  - test
  - deploy

# build:
#   image: docker
#   stage: build
#   services:
#     - name: docker:dind
#       alias: docker
#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - docker build -t $CI_REGISTRY/root/k8s-data/image:$CI_COMMIT_SHORT_SHA .
#     - docker push $CI_REGISTRY/root/k8s-data/image:$CI_COMMIT_SHORT_SHA


deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  variables:
    KUBE_CONTEXT: root/k8s-connection:k8s-connection
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl apply -f $CI_PROJECT_DRI/CD/.


    