version: '3'
#Define Services
services:
  db:
    image: mysql
    container_name: panel-db
    volumes:
       - .db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  backend:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
    - 8085:8000
    container_name: panel
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/app
    restart: always
    env_file:
      - .env
    depends_on:
       db:
        condition: service_healthy

