# Generated by Django 3.1.2 on 2020-11-01 11:04

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Make_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposeVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=25)),
                ('number_of_cores', models.IntegerField()),
                ('number_of_memory', models.IntegerField()),
                ('creation_of_vm', django_jalali.db.models.jDateTimeField()),
                ('describtion', models.TextField(blank=True, max_length=150)),
            ],
        ),
    ]
