# Generated by Django 3.1.2 on 2020-12-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Make_API', '0002_composevm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='composevm',
            options={'verbose_name': 'ماشین مجازی', 'verbose_name_plural': 'ماشین مجازی ها'},
        ),
        migrations.AlterField(
            model_name='composevm',
            name='creation_of_vm',
            field=models.DateTimeField(verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='composevm',
            name='describtion',
            field=models.TextField(blank=True, max_length=150, verbose_name='توضیخات'),
        ),
        migrations.AlterField(
            model_name='composevm',
            name='number_of_cores',
            field=models.IntegerField(verbose_name='تعداد هسته'),
        ),
        migrations.AlterField(
            model_name='composevm',
            name='number_of_memory',
            field=models.IntegerField(verbose_name='رم'),
        ),
        migrations.AlterField(
            model_name='composevm',
            name='vm_name',
            field=models.CharField(help_text='Inter Your vm name', max_length=25, verbose_name='نام ماشین مجازی'),
        ),
    ]
