apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: django-app-deploy
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30005
  selector:
    app: django-application
  type: NodePort
